name: Despliegue a Raspberry Pi

on:
  push:
    branches: [ "WEB-II" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        clean: false 

  
    # Esto mueve el código nuevo del Runner a la carpeta real de la Web.
    # Excluimos .env y venv para no romper tu configuración secreta.
    - name: Deploy to Production Folder
      run: |
        rsync -av --exclude='.env' --exclude='venv' --exclude='.git' ./ /home/pardo/Trex-Project/

    # --- PASO DE SEGURIDAD (.ENV) ---
    # Nos aseguramos que el .env siga estando disponible para los comandos
    - name: Copiar Credenciales (.env)
      run: |
        cp /home/pardo/Trex-Project/.env .

    - name: Install Dependencies
      run: |
        source /home/pardo/Trex-Project/venv/bin/activate
        pip install -r requirements.txt

    - name: Apply Migrations
      run: |
        source /home/pardo/Trex-Project/venv/bin/activate
        python manage.py migrate

    - name: Collect Static
      run: |
        source /home/pardo/Trex-Project/venv/bin/activate
        echo "yes" | python manage.py collectstatic

    - name: Restart Gunicorn
      run: |
        sudo /usr/bin/systemctl restart gunicorn