name: Django CI/CD Workflow

on:
  push:
    branches: [ "main", "WEB-II" ]  # rama
  pull_request:
    branches: [ "main", "WEB-II" ] 

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11] 

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    # Creamos un .env falso para que las pruebas no fallen
    - name: Create dummy .env file
      run: |
        echo "SECRET_KEY=django-insecure-test-key-for-ci" > .env
        echo "DEBUG=True" >> .env
        echo "DB_NAME=trex" >> .env
        echo "DB_USER=root" >> .env
        echo "DB_PASSWORD=root" >> .env
        echo "DB_HOST=localhost" >> .env
        echo "DB_PORT=3306" >> .env
        
    # Ejecutamos el chequeo de seguridad y configuraci√≥n de Django
    - name: Run Django System Checks
      run: |
        python manage.py check

    # Ejecutamos los tests
    - name: Run Tests
      run: |
        python manage.py test